# Makefile generated by imake - do not edit!
# $XConsortium: imake.c,v 1.37 88/10/08 20:08:30 jim Exp $
#
# The cpp used on this machine replaces all newlines and multiple tabs and
# spaces in a macro expansion with a single space.  Imake tries to compensate
# for this, but is not always successful.
#

###########################################################################
# X Window System Makefile generated from template file Imake.tmpl
# $XConsortium: Imake.tmpl,v 1.91 88/10/23 22:37:10 jim Exp $
#
# Do not change the body of the imake template file.  Server-specific
# parameters may be set in the appropriate .macros file; site-specific
# parameters (but shared by all servers) may be set in site.def.  If you
# make any changes, you'll need to rebuild the makefiles using
# "make World" (at best) or "make Makefile; make Makefiles" (at least) in
# the top level directory.
#
# If your C preprocessor doesn't define any unique symbols, you'll need
# to set BOOTSTRAPCFLAGS when rebuilding imake (usually when doing
# "make Makefile", "make Makefiles", or "make World").
#
# If you absolutely can't get imake to work, you'll need to set the
# variables at the top of each Makefile as well as the dependencies at the
# bottom (makedepend will do this automatically).
#

###########################################################################
# platform-specific configuration parameters - edit Sun.macros to change

# platform:  $XConsortium: Sun.macros,v 1.52 88/10/23 11:00:55 jim Exp $
# operating system:   SunOS 3.4

BOOTSTRAPCFLAGS =
             AS = as
             CC = cc
            CPP = /lib/cpp
             LD = ld
           LINT = lint
        INSTALL = install
           TAGS = ctags
             RM = rm -f
             MV = mv
             LN = ln -s
         RANLIB = ranlib
RANLIBINSTFLAGS = -t
             AR = ar clq
             LS = ls
       LINTOPTS = -axz
    LINTLIBFLAG = -C
           MAKE = make
STD_CPP_DEFINES =
    STD_DEFINES =

###########################################################################
# site-specific configuration parameters - edit site.def to change

# site:  $XConsortium: site.def,v 1.16 88/10/12 10:30:24 jim Exp $

###########################################################################
# definitions common to all Makefiles - do not edit

          SHELL =  /bin/sh

        DESTDIR =
      USRLIBDIR = $(DESTDIR)/usr/lib
         BINDIR = $(DESTDIR)/usr/bin/X11
         INCDIR = $(DESTDIR)/usr/include/X11
         ADMDIR = $(DESTDIR)/usr/adm
         LIBDIR = $(USRLIBDIR)/X11
     LINTLIBDIR = $(USRLIBDIR)/lint
        FONTDIR = $(LIBDIR)/fonts
       XINITDIR = $(LIBDIR)/xinit
         XDMDIR = $(LIBDIR)/xdm
         UWMDIR = $(LIBDIR)/uwm
         AWMDIR = $(LIBDIR)/awm
         TWMDIR = $(LIBDIR)/twm
        MANPATH = $(DESTDIR)/usr/man
  MANSOURCEPATH = $(MANPATH)/man
         MANDIR = $(MANSOURCEPATH)n
      LIBMANDIR = $(MANSOURCEPATH)3
    XAPPLOADDIR = $(LIBDIR)/app-defaults

   INSTBINFLAGS = -m 0755
   INSTUIDFLAGS = -m 4755
   INSTLIBFLAGS = -m 0664
   INSTINCFLAGS = -m 0444
   INSTMANFLAGS = -m 0444
   INSTAPPFLAGS = -m 0444
  INSTKMEMFLAGS = -m 4755
        FCFLAGS = -t
    CDEBUGFLAGS = -O

        PATHSEP = /
         DEPEND = $(DEPENDSRC)/makedepend
          IMAKE = $(IMAKESRC)/imake
            RGB = $(RGBSRC)/rgb
             FC = $(BDFTOSNFSRC)/bdftosnf
      MKFONTDIR = $(MKFONTDIRSRC)/mkfontdir
      MKDIRHIER = $(SCRIPTSSRC)/mkdirhier.sh

         CFLAGS = $(CDEBUGFLAGS) $(INCLUDES) $(STD_DEFINES) $(DEFINES)
      LINTFLAGS = $(LINTOPTS) $(INCLUDES) $(STD_DEFINES) $(DEFINES) -DLINT
        LDFLAGS = $(CDEBUGFLAGS) $(SYS_LIBRARIES) $(SYSAUX_LIBRARIES)
            TOP = ../../.
      CLIENTSRC = $(TOP)/clients
        DEMOSRC = $(TOP)/demos
         LIBSRC = $(TOP)/lib
        FONTSRC = $(TOP)/fonts
     INCLUDESRC = $(TOP)/X11
      SERVERSRC = $(TOP)/server
        UTILSRC = $(TOP)/util
     SCRIPTSSRC = $(UTILSRC)/scripts
     EXAMPLESRC = $(TOP)/examples
     CONTRIBSRC = $(TOP)/contrib
         DOCSRC = $(TOP)/doc
         RGBSRC = $(TOP)/rgb
      DEPENDSRC = $(UTILSRC)/makedepend
       IMAKESRC = $(UTILSRC)/imake
       IRULESRC = $(UTILSRC)/imake.includes
        XLIBSRC = $(LIBSRC)/X
         XMUSRC = $(LIBSRC)/Xmu
     TOOLKITSRC = $(LIBSRC)/Xt
     AWIDGETSRC = $(LIBSRC)/Xaw
     OLDXLIBSRC = $(LIBSRC)/oldX
    BDFTOSNFSRC = $(FONTSRC)/bdftosnf
   MKFONTDIRSRC = $(FONTSRC)/mkfontdir
   EXTENSIONSRC = $(TOP)/extensions
   EXTENSIONLIB = $(EXTENSIONSRC)/lib/libXext.a
           XLIB = $(XLIBSRC)/libX11.a
         XMULIB = $(XMUSRC)/libXmu.a
        OLDXLIB = $(OLDXLIBSRC)/liboldX.a
       XTOOLLIB = $(TOOLKITSRC)/libXt.a
         XAWLIB = $(AWIDGETSRC)/libXaw.a
       LINTXLIB = $(XLIBSRC)/llib-lX11.ln
        LINTXMU = $(XMUSRC)/llib-lXmu.ln
      LINTXTOOL = $(TOOLKITSRC)/llib-lXt.ln
        LINTXAW = $(AWIDGETSRC)/llib-lXaw.ln
       INCLUDES = -I$(TOP)
      MACROFILE = Sun.macros
   ICONFIGFILES = $(IRULESRC)/Imake.tmpl \
			$(IRULESRC)/$(MACROFILE) $(IRULESRC)/site.def
  IMAKE_DEFINES =
      IMAKE_CMD = $(NEWTOP)$(IMAKE) -TImake.tmpl -I$(NEWTOP)$(IRULESRC) \
			-s Makefile $(IMAKE_DEFINES)
         RM_CMD = $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a \
			.emacs_* tags TAGS make.log MakeOut

###########################################################################
# rules:  $XConsortium: Imake.rules,v 1.71 88/10/23 22:46:34 jim Exp $

###########################################################################
# start of Imakefile

###########################################################################
#                                                                         #
#                         Attention xterm porters                         #
#                                                                         #
#                                                                         #
# Xterm assumes that bcopy can handle overlapping arguments.  If your     #
# bcopy (or memcpy) can't, write a routine called Bcopy that can and      #
# the -DBcopy argument from the DEFINES list given below.  If possible,   #
# try to avoid extra procedure calls as this routine is used a lot.       #
#                                                                         #
###########################################################################

        DEFINES = -DMODEMENU -DUTMP -DBcopy=bcopy
          SRCS1 = button.c charproc.c cursor.c data.c input.c \
		  main.c menu.c misc.c screen.c scrollbar.c tabs.c \
		  TekPrsTbl.c Tekproc.c util.c VTPrsTbl.c
          OBJS1 = main.o input.o charproc.o cursor.o util.o tabs.o \
		  screen.o scrollbar.o button.o Tekproc.o misc.o \
		  VTPrsTbl.o TekPrsTbl.o data.o menu.o
          SRCS2 = resize.c
          OBJS2 = resize.o
       PROGRAMS = resize xterm
   INSTALLFLAGS = $(INSTUIDFLAGS)
       INCLUDES = -I$(TOOLKITSRC) -I$(TOP)

 OBJS = $(OBJS1) $(OBJS2) $(OBJS3)
 SRCS = $(SRCS1) $(SRCS2) $(SRCS3)

all:: $(PROGRAMS)

xterm: $(OBJS1) $(XAWLIB) $(XMULIB) $(XTOOLLIB) $(XLIB)
	$(RM) $@
	$(CC) -o $@ $(OBJS1) $(XAWLIB) $(XMULIB) $(XTOOLLIB) $(XLIB) $(LDFLAGS) -ltermcap $(SYSLAST_LIBRARIES)

install:: xterm
	$(INSTALL) -c $(INSTALLFLAGS) xterm $(BINDIR)

install.man:: xterm.man
	$(INSTALL) -c $(INSTMANFLAGS) xterm.man $(MANDIR)/xterm.n

relink::
	$(RM) $(PROGRAMS)
	$(MAKE) $(MFLAGS) $(PROGRAMS)

depend:: $(DEPEND)

depend::
	$(DEPEND) -s "# DO NOT DELETE" -- $(CFLAGS) -- $(SRCS)

$(DEPEND):
	@echo "making $@"; \
	cd $(DEPENDSRC); $(MAKE)

clean::
	$(RM) $(PROGRAMS)

resize: $(OBJS2)
	$(RM) $@
	$(CC) -o $@ $(OBJS2)  $(LDFLAGS) -lc -ltermcap $(SYSLAST_LIBRARIES)

relink::
	$(RM) resize
	$(MAKE) $(MFLAGS) resize

clean::
	$(RM) resize

install:: resize
	$(INSTALL) -c   resize  $(BINDIR)

install.man:: resize.man
	$(INSTALL) -c $(INSTMANFLAGS) resize.man $(MANDIR)/resize.n

###########################################################################
# Imake.tmpl common rules for all Makefiles - do not edit

emptyrule::

clean::
	$(RM_CMD) \#*

Makefile:: $(IMAKE)

Makefile:: Imakefile \
	$(IRULESRC)/Imake.tmpl \
	$(IRULESRC)/Imake.rules \
	$(IRULESRC)/site.def \
	$(IRULESRC)/$(MACROFILE)
	-@if [ -f Makefile ]; then \
	echo "$(RM) Makefile.bak; $(MV) Makefile Makefile.bak"; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP)

$(IMAKE):
	@echo "making $@"; \
	cd $(IMAKESRC); $(MAKE) BOOTSTRAPCFLAGS=$(BOOTSTRAPCFLAGS)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

###########################################################################
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install done"

install.man::
	@echo "install.man done"

Makefiles::

###########################################################################
# dependencies generated by makedepend

# DO NOT DELETE

button.o: ../.././X11/copyright.h ../.././X11/Xos.h /usr/include/sys/types.h
button.o: /usr/include/sys/sysmacros.h /usr/include/strings.h
button.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
button.o: /usr/include/sys/time.h /usr/include/sys/time.h ../.././X11/Xlib.h
button.o: ../.././X11/X.h ../.././X11/Xatom.h ../.././X11/Xmu.h
button.o: ../.././X11/Intrinsic.h ../.././X11/Xutil.h ../.././X11/Xresource.h
button.o: ../.././X11/Core.h ../.././X11/Composite.h ../.././X11/Constraint.h
button.o: /usr/include/stdio.h /usr/include/signal.h /usr/include/setjmp.h
button.o: /usr/include/ctype.h ptyx.h ../.././X11/IntrinsicP.h
button.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h
button.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h data.h error.h
button.o: menu.h
charproc.o: ../.././X11/copyright.h /usr/include/stdio.h /usr/include/sgtty.h
charproc.o: /usr/include/sys/ioctl.h /usr/include/sys/ttychars.h
charproc.o: /usr/include/sys/ttydev.h /usr/include/ctype.h
charproc.o: /usr/include/errno.h /usr/include/sys/errno.h
charproc.o: /usr/include/setjmp.h ptyx.h ../.././X11/Xos.h
charproc.o: /usr/include/sys/types.h /usr/include/sys/sysmacros.h
charproc.o: /usr/include/strings.h /usr/include/sys/file.h
charproc.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
charproc.o: /usr/include/sys/time.h ../.././X11/Xlib.h ../.././X11/X.h
charproc.o: ../.././X11/IntrinsicP.h ../.././X11/Intrinsic.h
charproc.o: ../.././X11/CoreP.h ../.././X11/CompositeP.h
charproc.o: ../.././X11/ConstrainP.h VTparse.h data.h ../.././X11/Intrinsic.h
charproc.o: ../.././X11/Xutil.h ../.././X11/Xresource.h ../.././X11/Core.h
charproc.o: ../.././X11/Composite.h ../.././X11/Constraint.h error.h main.h
charproc.o: ../.././X11/StringDefs.h menu.h
cursor.o: ../.././X11/copyright.h ../.././X11/Xlib.h /usr/include/sys/types.h
cursor.o: /usr/include/sys/sysmacros.h ../.././X11/X.h /usr/include/stdio.h
cursor.o: /usr/include/sys/ioctl.h /usr/include/sys/ttychars.h
cursor.o: /usr/include/sys/ttydev.h ptyx.h ../.././X11/Xos.h
cursor.o: /usr/include/strings.h /usr/include/sys/file.h
cursor.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
cursor.o: /usr/include/sys/time.h ../.././X11/IntrinsicP.h
cursor.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h
cursor.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h
data.o: ../.././X11/copyright.h /usr/include/setjmp.h ../.././X11/Xlib.h
data.o: /usr/include/sys/types.h /usr/include/sys/sysmacros.h ../.././X11/X.h
data.o: ../.././X11/Intrinsic.h ../.././X11/Xutil.h ../.././X11/Xresource.h
data.o: ../.././X11/Xos.h /usr/include/strings.h /usr/include/sys/file.h
data.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
data.o: /usr/include/sys/time.h ../.././X11/Core.h ../.././X11/Composite.h
data.o: ../.././X11/Constraint.h ptyx.h ../.././X11/IntrinsicP.h
data.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h ../.././X11/CompositeP.h
data.o: ../.././X11/ConstrainP.h data.h
input.o: ../.././X11/copyright.h ../.././X11/Xlib.h /usr/include/sys/types.h
input.o: /usr/include/sys/sysmacros.h ../.././X11/X.h ../.././X11/keysym.h
input.o: ../.././X11/keysymdef.h ../.././X11/DECkeysym.h
input.o: ../.././X11/Intrinsic.h ../.././X11/Xutil.h ../.././X11/Xresource.h
input.o: ../.././X11/Xos.h /usr/include/strings.h /usr/include/sys/file.h
input.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
input.o: /usr/include/sys/time.h ../.././X11/Core.h ../.././X11/Composite.h
input.o: ../.././X11/Constraint.h /usr/include/stdio.h ptyx.h
input.o: ../.././X11/IntrinsicP.h ../.././X11/Intrinsic.h ../.././X11/CoreP.h
input.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h
main.o: ../.././X11/copyright.h ../.././X11/Xos.h /usr/include/sys/types.h
main.o: /usr/include/sys/sysmacros.h /usr/include/strings.h
main.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
main.o: /usr/include/sys/time.h /usr/include/sys/time.h ../.././X11/Xlib.h
main.o: ../.././X11/X.h /usr/include/pwd.h /usr/include/ctype.h
main.o: /usr/include/sgtty.h /usr/include/sys/ioctl.h
main.o: /usr/include/sys/ttychars.h /usr/include/sys/ttydev.h
main.o: /usr/include/sys/wait.h /usr/include/sys/resource.h
main.o: /usr/include/stdio.h /usr/include/errno.h /usr/include/sys/errno.h
main.o: /usr/include/signal.h /usr/include/setjmp.h /usr/include/utmp.h
main.o: /usr/include/sys/param.h /usr/include/machine/param.h ptyx.h
main.o: ../.././X11/IntrinsicP.h ../.././X11/Intrinsic.h ../.././X11/CoreP.h
main.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h data.h
main.o: ../.././X11/Intrinsic.h ../.././X11/Xutil.h ../.././X11/Xresource.h
main.o: ../.././X11/Core.h ../.././X11/Composite.h ../.././X11/Constraint.h
main.o: error.h main.h ../.././X11/StringDefs.h ../.././X11/Shell.h
main.o: ../.././X11/Vendor.h
menu.o: ../.././X11/copyright.h /usr/include/stdio.h ../.././X11/Xlib.h
menu.o: /usr/include/sys/types.h /usr/include/sys/sysmacros.h ../.././X11/X.h
menu.o: ../.././X11/StringDefs.h ../.././X11/Intrinsic.h ../.././X11/Xutil.h
menu.o: ../.././X11/Xresource.h ../.././X11/Xos.h /usr/include/strings.h
menu.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
menu.o: /usr/include/sys/time.h /usr/include/sys/time.h ../.././X11/Core.h
menu.o: ../.././X11/Composite.h ../.././X11/Constraint.h ../.././X11/Shell.h
menu.o: ../.././X11/Xatom.h ../.././X11/cursorfont.h menu.h
menu.o: /usr/include/setjmp.h ptyx.h ../.././X11/IntrinsicP.h
menu.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h ../.././X11/CompositeP.h
menu.o: ../.././X11/ConstrainP.h data.h
misc.o: ../.././X11/copyright.h ../.././X11/Xos.h /usr/include/sys/types.h
misc.o: /usr/include/sys/sysmacros.h /usr/include/strings.h
misc.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
misc.o: /usr/include/sys/time.h /usr/include/sys/time.h ../.././X11/Xlib.h
misc.o: ../.././X11/X.h /usr/include/stdio.h /usr/include/setjmp.h
misc.o: /usr/include/signal.h /usr/include/ctype.h /usr/include/pwd.h
misc.o: ../.././X11/Xutil.h ../.././X11/Xatom.h ptyx.h
misc.o: ../.././X11/IntrinsicP.h ../.././X11/Intrinsic.h ../.././X11/CoreP.h
misc.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h data.h
misc.o: ../.././X11/Intrinsic.h ../.././X11/Xresource.h ../.././X11/Core.h
misc.o: ../.././X11/Composite.h ../.././X11/Constraint.h error.h
misc.o: ../.././X11/cursorfont.h gray.ic wait.ic waitmask.ic
misc.o: ../.././X11/Shell.h
screen.o: ../.././X11/copyright.h ../.././X11/Xlib.h /usr/include/sys/types.h
screen.o: /usr/include/sys/sysmacros.h ../.././X11/X.h /usr/include/stdio.h
screen.o: /usr/include/sys/ioctl.h /usr/include/sys/ttychars.h
screen.o: /usr/include/sys/ttydev.h /usr/include/signal.h ptyx.h
screen.o: ../.././X11/Xos.h /usr/include/strings.h /usr/include/sys/file.h
screen.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
screen.o: /usr/include/sys/time.h ../.././X11/IntrinsicP.h
screen.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h
screen.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h error.h
scrollbar.o: ../.././X11/copyright.h /usr/include/stdio.h
scrollbar.o: /usr/include/setjmp.h ../.././X11/Xlib.h
scrollbar.o: /usr/include/sys/types.h /usr/include/sys/sysmacros.h
scrollbar.o: ../.././X11/X.h ../.././X11/Xatom.h ../.././X11/Xutil.h
scrollbar.o: ../.././X11/StringDefs.h ptyx.h ../.././X11/Xos.h
scrollbar.o: /usr/include/strings.h /usr/include/sys/file.h
scrollbar.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
scrollbar.o: /usr/include/sys/time.h ../.././X11/IntrinsicP.h
scrollbar.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h
scrollbar.o: ../.././X11/CompositeP.h ../.././X11/ConstrainP.h data.h
scrollbar.o: ../.././X11/Intrinsic.h ../.././X11/Xresource.h
scrollbar.o: ../.././X11/Core.h ../.././X11/Composite.h
scrollbar.o: ../.././X11/Constraint.h ../.././X11/Scroll.h ../.././X11/Xmu.h
scrollbar.o: error.h ../.././X11/Shell.h
tabs.o: ../.././X11/copyright.h ../.././X11/Xlib.h /usr/include/sys/types.h
tabs.o: /usr/include/sys/sysmacros.h ../.././X11/X.h ptyx.h ../.././X11/Xos.h
tabs.o: /usr/include/strings.h /usr/include/sys/file.h
tabs.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
tabs.o: /usr/include/sys/time.h ../.././X11/IntrinsicP.h
tabs.o: ../.././X11/Intrinsic.h ../.././X11/CoreP.h ../.././X11/CompositeP.h
tabs.o: ../.././X11/ConstrainP.h
TekPrsTbl.o: ../.././X11/copyright.h Tekparse.h
Tekproc.o: ../.././X11/copyright.h ../.././X11/Xos.h /usr/include/sys/types.h
Tekproc.o: /usr/include/sys/sysmacros.h /usr/include/strings.h
Tekproc.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
Tekproc.o: /usr/include/sys/time.h /usr/include/sys/time.h ../.././X11/Xlib.h
Tekproc.o: ../.././X11/X.h ../.././X11/Intrinsic.h ../.././X11/Xutil.h
Tekproc.o: ../.././X11/Xresource.h ../.././X11/Core.h ../.././X11/Composite.h
Tekproc.o: ../.././X11/Constraint.h ../.././X11/Xatom.h
Tekproc.o: ../.././X11/StringDefs.h ../.././X11/Shell.h ptyx.h
Tekproc.o: ../.././X11/IntrinsicP.h ../.././X11/Intrinsic.h
Tekproc.o: ../.././X11/CoreP.h ../.././X11/CompositeP.h
Tekproc.o: ../.././X11/ConstrainP.h Tekparse.h /usr/include/stdio.h
Tekproc.o: /usr/include/sgtty.h /usr/include/sys/ioctl.h
Tekproc.o: /usr/include/sys/ttychars.h /usr/include/sys/ttydev.h
Tekproc.o: /usr/include/ctype.h /usr/include/errno.h /usr/include/sys/errno.h
Tekproc.o: /usr/include/setjmp.h /usr/include/pwd.h data.h error.h menu.h
util.o: ../.././X11/copyright.h /usr/include/stdio.h ../.././X11/Xlib.h
util.o: /usr/include/sys/types.h /usr/include/sys/sysmacros.h ../.././X11/X.h
util.o: ../.././X11/Intrinsic.h ../.././X11/Xutil.h ../.././X11/Xresource.h
util.o: ../.././X11/Xos.h /usr/include/strings.h /usr/include/sys/file.h
util.o: /usr/include/sys/fcntl.h /usr/include/sys/time.h
util.o: /usr/include/sys/time.h ../.././X11/Core.h ../.././X11/Composite.h
util.o: ../.././X11/Constraint.h /usr/include/signal.h /usr/include/setjmp.h
util.o: ptyx.h ../.././X11/IntrinsicP.h ../.././X11/Intrinsic.h
util.o: ../.././X11/CoreP.h ../.././X11/CompositeP.h ../.././X11/ConstrainP.h
util.o: data.h error.h
VTPrsTbl.o: ../.././X11/copyright.h VTparse.h
resize.o: ../.././X11/copyright.h ../.././X11/Xos.h /usr/include/sys/types.h
resize.o: /usr/include/sys/sysmacros.h /usr/include/strings.h
resize.o: /usr/include/sys/file.h /usr/include/sys/fcntl.h
resize.o: /usr/include/sys/time.h /usr/include/sys/time.h
resize.o: /usr/include/stdio.h /usr/include/ctype.h /usr/include/sys/ioctl.h
resize.o: /usr/include/sys/ttychars.h /usr/include/sys/ttydev.h
resize.o: /usr/include/sgtty.h /usr/include/signal.h /usr/include/pwd.h
